### ISSUE TITLE
GOROOT not found

### ISSUE THREAD

**Issue by AienTech** [wangyoucao577/go-release-action#11]
here there, as the title suggests, I get the following error when trying to release a new binary:

```
Go Release Binaries                          13s
go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.14.6/x64
 79872K ........ ........ ........ ........ ........ ........ 68%  155M 0s
 82944K ........ ........ ........ ........ ........ ........ 71%  146M 0s
 86016K ........ ........ ........ ........ ........ ........ 73%  138M 0s
 89088K ........ ........ ........ ........ ........ ........ 76%  127M 0s
 92160K ........ ........ ........ ........ ........ ........ 78%  142M 0s
 95232K ........ ........ ........ ........ ........ ........ 81%  139M 0s
 98304K ........ ........ ........ ........ ........ ........ 84%  153M 0s
101376K ........ ........ ........ ........ ........ ........ 86%  144M 0s
104448K ........ ........ ........ ........ ........ ........ 89%  162M 0s
107520K ........ ........ ........ ........ ........ ........ 91%  149M 0s
110592K ........ ........ ........ ........ ........ ........ 94%  165M 0s
113664K ........ ........ ........ ........ ........ ........ 96%  141M 0s
116736K ........ ........ ........ ........ ........ ........ 99%  135M 0s
119808K ........ .....                                       100%  147M=1.0s

2020-08-06 10:28:57 (123 MB/s) - 'go-linux.tar.gz' saved [123550266/123550266]

++ tar -zxf go-linux.tar.gz
++ mv go /usr/local/
++ mkdir -p /go/bin /go/src /go/pkg
++ export GO_HOME=/usr/local/go
++ GO_HOME=/usr/local/go
++ export PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export GOPATH=/go
++ GOPATH=/go
+ go version
go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.14.6/x64
```

is there a way to fix it? or is it just my configuration? here is also my yaml file:

```
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.5
```

**Comment by wangyoucao577** [comment]
Yes, it's due to your yaml configuration. You don't need to set up Go, Get dependencies, etc, by manual. Please follow the example https://github.com/wangyoucao577/go-release-action#basic-example or https://github.com/wangyoucao577/go-release-action#advanced-example to setup your workflow. All the Go env, go mod, go build is already in  `wangyoucao577/go-release-action`, and mandatory parameters in this table https://github.com/wangyoucao577/go-release-action#parameters is necessary to let it work.          
If you still meet issue, please show me your repo and erro link, I can help to review more details.

**Comment by AienTech** [comment]
You're right, that eventually fixed the main issue, not I'm facing:

```
Run wangyoucao577/go-release-action@master18s
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: null
go: downloading github.com/urfave/cli/v2 v2.2.0
go: downloading github.com/iancoleman/strcase v0.0.0-20191112232945-16388991a334
go: downloading github.com/ddliu/go-httpclient v0.6.7
go: downloading github.com/juju/ansiterm v0.0.0-20180109212912-720a0952cc2a
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/mattn/go-isatty v0.0.4
go: downloading github.com/mattn/go-colorable v0.0.9
go: downloading github.com/lunixbochs/vtclean v0.0.0-20180621232353-2d01aacdc34a
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
+ cd build-artifacts-1596799156
+ ls -lh
total 12M
-rwxr-xr-x 1 root root 12M Aug  7 11:19 quire-cli
+ RELEASE_ASSET_EXT=.tar.gz
+ '[' linux == windows ']'
+ tar cvfz quire-cli-master-linux-amd64.tar.gz quire-cli
quire-cli
++ md5sum quire-cli-master-linux-amd64.tar.gz
++ cut -d ' ' -f 1
+ MD5_SUM=9ee778f2f2ca05ba2c13f054df848883
+ curl --fail -X POST --data-binary @quire-cli-master-linux-amd64.tar.gz -H 'Content-Type: application/gzip' -H 'Authorization: Bearer ***' 'null?name=quire-cli-master-linux-amd64.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: null
```

Here's also the repo: [https://github.com/AienTech/quire-cli](https://github.com/AienTech/quire-cli)

**Comment by wangyoucao577** [comment]
You're using wrong event to trigger the action.      
Please use       
```
on: 
  release:
    types: [created]
```
instead of        
```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
in your workflow and then try again. You're supposed to create a new release [here ](https://github.com/AienTech/quire-cli/releases) to trigger the release event as target of binaries.
