### ISSUE TITLE
Could not resolve Host : Null

### ISSUE THREAD

**Issue by sumitkolhe** [wangyoucao577/go-release-action#12]
```
+ curl --fail -X POST --data-binary @kinto-v1.9-linux-386.tar.gz -H 'Content-Type: application/gzip' -H 'Authorization: Bearer ***' 'null?name=kinto-v1.9-linux-386.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: null
##[error]The operation was canceled
```

Getting this error when trying to build a binary files with ldflags enabled.

**Comment by wangyoucao577** [comment]
Could you please show me a little more details, maybe the link of your `yaml`?  It looks like something wrong in your configuraiton.

**Comment by sumitkolhe** [comment]
```
name: Build and Release Binaries
on:
  push:
    tags:
      - "v*"
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Set APP_VERSION env
      run: echo ::set-env name=CLI_VERSION::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        binary_name: "kinto"
        ldflags: -X "github.com/sumitkolhe/cli/internal/config.Version=${{ env.CLI_VERSION }}
```

heres the yaml
