### ISSUE TITLE
apt-get install pkg via pre_command fail

### ISSUE THREAD

**Issue by hujun-open** [wangyoucao577/go-release-action#128]
here is my YAML:
```
# .github/workflows/release.yaml
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    permissions: write-all
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64,arm64]
        
    steps:

    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: "apt-get -y install libpcap-dev"
```

however it fails with error message:  I wonder what did I miss?
```
 ++ apt-get -y install libpcap-dev
E: Unable to locate package libpcap-dev
```
