### ISSUE TITLE
Error when running `go build`

### ISSUE THREAD

**Issue by gurgenyegoryan** [wangyoucao577/go-release-action#132]
Hello everyone, can someone help me figure out what this error means and how to solve it.

### Workflow:
```
- uses: wangyoucao577/go-release-action@v1
      with:
        pre_command: cd golang && make -C ../c build && mv ../c/libusearch.so libusearch.a && go test -v && cd ../
        github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: https://dl.google.com/go/go1.15.linux-amd64.tar.gz
        project_path: "./golang"
        build_flags: "-a -v -o usearch"
        binary_name: "usearch"
        release_tag: "v0.1.1"
        extra_files: LICENSE README.md
```

### Error:
```
go build github.com/unum-cloud/usearch/golang: build constraints exclude all Go files in /github/workspace/golang
```
