### ISSUE TITLE
Doubt: this action works when the tag is created by another actions?

### ISSUE THREAD

**Issue by gabriel-henriq** [wangyoucao577/go-release-action#137]
Looks like the `release`  trigger only works when the tag is created manually. Is right or Im doing something wrong?

I have two actions, one for binaries and another for changelog and tags managing.

```yaml
name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --prod --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release

```

```yaml
name: Go Binary Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
```

Source Code: https://github.com/gabriel-henriq/workflow-tests

Im very newbie on actions workflow, there's a way to retrieve the version generated on the previous flow (If I use the same action)?

**Comment by gabriel-henriq** [comment]
Actually I get around by adding a extra github actions just to fetch the latest tag, then I used in the next stage, so look likes this:

```yaml
name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --prod --frozen-lockfile

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Release Go Bin'
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.21.0
          release_tag: ${{ steps.previoustag.outputs.tag }}
          project_path: "./cmd/app"
```
