### ISSUE TITLE
Exclude some os/arch combinations from upx

### ISSUE THREAD

**Issue by xpufx** [wangyoucao577/go-release-action#140]
Is there a  config syntax to be able to accomplish this already? There are some combinations which upx does not support so they should be excluded.

**Comment by wangyoucao577** [comment]
It there a list that what os/arch `upx` currently supports? Maybe we can ignore it if out of the list.

**Comment by xpufx** [comment]
For my installed 4.2.1 version (on openSUSE Tumbleweed) the help text provides the following list.

> This version supports:
>     amd64-darwin.dylib                   dylib/amd64
>     amd64-darwin.macho                   macho/amd64
>     amd64-linux.elf                      linux/amd64
>     amd64-linux.kernel.vmlinux           vmlinux/amd64
>     amd64-win64.pe                       win64/pe
>     arm-darwin.macho                     macho/arm
>     arm-linux.elf                        linux/arm
>     arm-linux.kernel.vmlinux             vmlinux/arm
>     arm-linux.kernel.vmlinuz             vmlinuz/arm
>     arm-wince.pe                         wince/arm
>     arm64-darwin.macho                   macho/arm64
>     arm64-linux.elf                      linux/arm64
>     armeb-linux.elf                      linux/armeb
>     armeb-linux.kernel.vmlinux           vmlinux/armeb
>     fat-darwin.macho                     macho/fat
>     i086-dos16.com                       dos/com
>     i086-dos16.exe                       dos/exe
>     i086-dos16.sys                       dos/sys
>     i386-bsd.elf.execve                  bsd.exec/i386
>     i386-darwin.macho                    macho/i386
>     i386-dos32.djgpp2.coff               djgpp2/coff
>     i386-dos32.tmt.adam                  tmt/adam
>     i386-dos32.watcom.le                 watcom/le
>     i386-freebsd.elf                     freebsd/i386
>     i386-linux.elf                       linux/i386
>     i386-linux.elf.execve                linux.exec/i386
>     i386-linux.elf.shell                 linux.sh/i386
>     i386-linux.kernel.bvmlinuz           bvmlinuz/i386
>     i386-linux.kernel.vmlinux            vmlinux/i386
>     i386-linux.kernel.vmlinuz            vmlinuz/i386
>     i386-netbsd.elf                      netbsd/i386
>     i386-openbsd.elf                     openbsd/i386
>     i386-win32.pe                        win32/pe
>     m68k-atari.tos                       atari/tos
>     mips-linux.elf                       linux/mips
>     mipsel-linux.elf                     linux/mipsel
>     mipsel.r3000-ps1                     ps1/exe
>     powerpc-darwin.macho                 macho/ppc32
>     powerpc-linux.elf                    linux/ppc32
>     powerpc-linux.kernel.vmlinux         vmlinux/ppc32
>     powerpc64-linux.elf                  linux/ppc64
>     powerpc64le-linux.elf                linux/ppc64le
>     powerpc64le-linux.kernel.vmlinux     vmlinux/ppc64le

Ignoring combinations that do are not supported at all might be a good idea but there are still times when the executable format is supported but it might fail at runtime for whatever reason. I just had a few of those today with cryptic error messages for which I could not find a resolution. It might be good to implement exclude functionality going forward to exclude these without breaking the whole release.

For now I have resorted to using two separate release files, one with upx and one without. It seems to work fine when the os/arch combinations are put together correctly in their respective files. (People might actually do this also when they want both compressed and uncompressed binaries separately in their releases.)

**Comment by wangyoucao577** [comment]
Yes, this alternative is good enough. On the other hand, action level `exclude` might bring in more complexity but no more advantage. Let's keep it as is.

**Comment by xpufx** [comment]
This is sufficient for me as well. Thanks.

**Comment by lslqtz** [comment]
Specify these files that cannot be compiled in include and give a parameter, such as no_compress is set to true.
For example: using this will make all freebsd and linux riscv64 not use UPX.

```
    strategy:
      fail-fast: false
      matrix:
        goos: [freebsd]
        goarch: [386, amd64, arm64]
        - goos: linux
            goarch: 'riscv64'
            no_upx_compression: true
        - goos: freebsd
            no_upx_compression: true
 steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
    - name: 'Build +UPX'
      uses: 'wangyoucao577/go-release-action@v1'
      if: ${{ matrix.no_upx_compression != true }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: '-w'
        executable_compression: 'upx -v -9'
        goversion: 1.21
    - name: 'Build -UPX'
      uses: 'wangyoucao577/go-release-action@v1'
      if: ${{ matrix.no_upx_compression == true }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: '-w'
        goversion: 1.21
```
