### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by sech1p** [wangyoucao577/go-release-action#141]
Hello, i'm trying to build binary but go workflow returns me `build constraints exclude all Go files` error

i've tried using `go mod tidy` command before but without results.

```yaml
- name: Build Release 🛠 (Windows)
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          project_path: "./src"
        env:
          CGO_ENABLED: 1
```
