### ISSUE TITLE
releasing on git tag

### ISSUE THREAD

**Issue by stevenaldinger** [wangyoucao577/go-release-action#16]
Is there a way to pass in the release name? I don't want to have to manually create releases, I want to be able to push to a git tag, automatically create a release, and then upload binaries to it.

I tried using two separate actions, one that creates a release and then a separate one that is triggered on release. The second action was never actually triggered but I'd rather not work around the core issue anyway, I want it to be in one job.

the following action gets the `curl: (6) Could not resolve host: null` error.

```yaml
name: Build and Release Binaries

on:
  push:
    tags:
    # Push events to matching v*, i.e. v1.0, v20.15.10
    - 'v*'

jobs:
 create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-and-release-github:
    needs: [create-release]
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        project_path: "./client"
        binary_name: "client"
        build_flags: -v

```
