### ISSUE TITLE
GOARM 会影响 ARM64 构建产物的文件名

### ISSUE THREAD

**Issue by Simple-Tracker** [wangyoucao577/go-release-action#167]
若在变量中使用 GOARM (尤其是在 matrix 中为所有 OS/Arch 设置默认 GOARM 时), 会使 GOARCH=ARM64 的产物文件名出现意想不到的情况, 如: Program-1.0-linux-arm64v6.tar.gz. 这似乎是由于 release.sh 中使用了宽泛匹配导致的.
 
Go 编译器使用精确匹配, 摘自文档: https://pkg.go.dev/cmd/go/internal/help@go1.19.13
	GOARM
		For GOARCH=arm, the ARM architecture for which to compile.
		Valid values are 5, 6, 7.

关于 GOARM64: https://github.com/golang/go/issues/60905

示例 matrix:
```
    strategy:
      matrix:
        goos: [linux]
        goarch: ['arm', 'arm64']
        goarm: ['6']
        include:
          - goos: linux
             goarch: 'arm'
             goarm: '7'
```
