### ISSUE TITLE
exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by libsgh** [wangyoucao577/go-release-action#17]
linux amd64 构建失败

**Comment by wangyoucao577** [comment]
log?

**Comment by libsgh** [comment]
是的,我用了mattn/go-sqlite3
```
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in $PATH
```

**Comment by wangyoucao577** [comment]
已添加支持，版本`gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`, 请用`wangyoucao577/go-release-action@master`再尝试下?

**Comment by libsgh** [comment]
> 已添加支持，版本`gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`, 请用`wangyoucao577/go-release-action@master`再尝试下?

打包没问题了，我还用了packr能否在go build之前安装下，我添加`pre_command: "go get -u github.com/gobuffalo/packr/v2/packr2"`不起作用

**Comment by wangyoucao577** [comment]
能否给下log的link看下?

**Comment by libsgh** [comment]
> 能否给下log的link看下?

https://github.com/libsgh/PanIndex/commit/1ca5aeb21a44ed899a95170502532d6d9aa65686/checks/1089302532/logs

**Comment by wangyoucao577** [comment]
log看work都很正常。`pre_command`是用来解决没有使用`go mod`的仓库的依赖的，你的repo依赖已经通过`go mod`解决好了，不需要`pre_command`。你是想要把`packr2`也release到你的仓库的release page？还是？

**Comment by libsgh** [comment]
> log看work都很正常。`pre_command`是用来解决没有使用`go mod`的仓库的依赖的，你的repo依赖已经通过`go mod`解决好了，不需要`pre_command`。你是想要把`packr2`也release到你的仓库的release page？还是？

我的程序有一些页面和js等静态文件，使用[packr2](https://github.com/gobuffalo/packr/tree/master/v2) 可以把静态资源文件打包到二进制文件中，但需要在go build执行之前安装一下

**Comment by wangyoucao577** [comment]
可以提供个`go build`的wrap, 稍等

**Comment by libsgh** [comment]
> 可以提供个`go build`的wrap, 稍等

多谢，另外MD5文件是否可以配置不生成？

**Comment by wangyoucao577** [comment]
行吧，合理需求，一起给你加上

**Comment by wangyoucao577** [comment]
@libsgh 我这边没有实际使用`packr2`的项目，麻烦先用feature branch测试下: `wangyoucao577/go-release-action@feature/wrap-go-build`        
在你的workflow配置里面再加个参数: `build_command: 'packr2 build'`, 你之前加的`go get`的`pre_command`也要留着。试下看看是否work，有问题贴link

**Comment by libsgh** [comment]
```
steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@feature/wrap-go-build
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz"
          project_path: "./"
          binary_name: "PanIndex"
          pre_command: "go get -u github.com/gobuffalo/packr/v2/packr2"
          build_command: "packr2 build"
          extra_files: LICENSE README.md CHANGELOG.md
```

```
/release.sh: line 36: packr2: command not found
```
https://github.com/libsgh/PanIndex/commit/924a49d13d274c5a0350b3cfdb96bf7c44126e50/checks/1089793120/logs
