### ISSUE TITLE
Alpine Linux muslc build support

### ISSUE THREAD

**Issue by florensie** [wangyoucao577/go-release-action#33]
This is the workflow I currently have to publish builds:
```yml
on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux, windows and macos 32 and 64-bit x86
        goos: [linux, windows, darwin]
        goarch: [386, amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md
        sha256sum: false
        md5sum: false
```

The amd64 linux build does not run on alpine however because it uses muslc instead of glibc. Would it be possible to support this somehow or would I have to create a second job with `runs-on: alpine-latest`
