### ISSUE TITLE
github-assets-uploader fails with 404

### ISSUE THREAD

**Issue by jimsmart** [wangyoucao577/go-release-action#46]
Hi,

I am trying to setup your go-release-action, with no success so far.

I initially tried using it on a private repo. The output seems to show everything builds ok, but then github-assets-uploader gets a 404 when it attempts to use the GitHub API to get a list of the repo's release tags. I then tried using a private access token, via a secret, instead of using the default `${{ secrets.GITHUB_TOKEN }}`, but that also gives a 404, and the Action fails. (The permissions I have set for the access token are: repo, workflow, write:packages)

I then tried it on a public repo, assuming my previous issues/experience to be something to do with it being a private repo. But I am still encountering the same problem.

Here is the result of a run using the default GITHUB_TOKEN:
https://github.com/jimsmart/grobotstxt/actions/runs/767392532
Here is the result of a run using a private access token:
https://github.com/jimsmart/grobotstxt/actions/runs/767484813
— although they are both failing identically.

Direct link to one of the failures:
https://github.com/jimsmart/grobotstxt/runs/2391628287?check_suite_focus=true#step:4:204

The task fails at the same point, with the same 404, for the private repo also.

I have tried this with go-release-action v1.16 and the pre-release of v1.17

My release.yml

```yml
name: release

# on:
#   release:
#     types: [created]

on:
  push:
    tags:
      - "*"
      # - "v**"

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            goos: darwin

    steps:
      - uses: actions/checkout@v2
      # - uses: wangyoucao577/go-release-action@v1.17
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.ACTION_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/icanhasrobot"
          binary_name: "icanhasrobot"
          extra_files: LICENSE README.md
```

— Any ideas?
