### ISSUE TITLE
How to build multiple binaries and create multiple artifacts for them ? 

### ISSUE THREAD

**Issue by Milerius** [wangyoucao577/go-release-action#55]
Hello i read the documentation but not sure how to achieve this one:

- one server to build
- one client to build

and package them into 2 different artifacts

and especially how to do the equivalent of:

`go build -o binary_name package_name/my_file.go` ?

eg:

```yml
name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64]

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date -u +%Y-%m-%d-%H-%M) >> ${GITHUB_ENV}

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.17
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true          
          build_flags: cmd/mm2_tools_server.go
          binary_name: mm2-tools-server
 ```
 
 Generates: `go build -o build-artifacts-1626342834/mm2-tools-server cmd/mm2_tools_server.go ''`
 
 instead of `go build -o build-artifacts-1626342834/mm2-tools-server cmd/mm2_tools_server.go`
 
 Seems to be a mistake
