### ISSUE TITLE
Invalid usage of empty arguments using `go build path_to_filename`

### ISSUE THREAD

**Issue by Milerius** [wangyoucao577/go-release-action#56]
https://github.com/wangyoucao577/go-release-action/blob/caa90c8f6c9282530b71612c6982621aadad1699/release.sh#L41-L50

If you do not specify any LDFLAGS it's will generate an empty argument '' and therefore the action will not be able to build

eg:

```yml
- name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.17
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true
          build_flags: cmd/mm2_tools_server.go
          binary_name: mm2-tools-server
```

Will generate invalid command line with a `''` extra args.

` go build -o build-artifacts-1626343191/mm2-tools-server cmd/mm2_tools_server.go ''`

<img width="1269" alt="Capture d’écran 2021-07-15 à 12 08 33" src="https://user-images.githubusercontent.com/21139416/125770846-761e6909-1aa7-43ec-9878-2a4ca5010eea.png">
