### ISSUE TITLE
write: connection reset by peer

### ISSUE THREAD

**Issue by ioogle** [wangyoucao577/go-release-action#62]
Hi youcao, thanks for your great work.

I came across a random error:

```
Post "https://uploads.github.com/repos/ioogle/xxx/releases/52036860/assets?name=xxx-api-v0.0.4-darwin-amd64.tar.gz": write tcp 172.17.0.2:39572->140.82.114.13:443: write: connection reset by peer
```

But sometimes it works fine. 

This is the action:

```
name: Release Go Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      GOPRIVATE: github.com/ioogle
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}

      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - name: Build Go Binary
        uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/api"
          binary_name: "xxx-api"
          pre_command: "cd ./xxx; git config --global url.\"https://ioogle:${{ secrets.ACCESS_TOKEN }}@github.com\".insteadOf \"https://github.com\"; go mod download"
          ldflags: -X "main.appVersion=${{ github.event.release.tag_name }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
          asset_name: xxx-api-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
```

**Comment by rsubr** [comment]
I'm getting a different error from the `github-assets-uploader` while running my [release.yml](https://github.com/rsubr/onerror/blob/master/.github/workflows/release.yml) and all the builds fail.

```
+ github-assets-uploader -f onerror-master-linux-amd64.tar.gz -mediatype application/gzip -repo rsubr/onerror -token *** -tag master
Post "https://uploads.github.com/repos/rsubr/onerror/releases/52562171/assets?name=onerror-master-linux-amd64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 1; REFUSED_STREAM] after Request.Body was written; define Request.GetBody to avoid this error
```

Do you need more logs?

**Comment by wangyoucao577** [comment]
> I'm getting a different error from the `github-assets-uploader` while running my [release.yml](https://github.com/rsubr/onerror/blob/master/.github/workflows/release.yml) and all the builds fail.
> 
> ```
> + github-assets-uploader -f onerror-master-linux-amd64.tar.gz -mediatype application/gzip -repo rsubr/onerror -token *** -tag master
> Post "https://uploads.github.com/repos/rsubr/onerror/releases/52562171/assets?name=onerror-master-linux-amd64.tar.gz": http2: Transport: cannot retry err [stream error: stream ID 1; REFUSED_STREAM] after Request.Body was written; define Request.GetBody to avoid this error
> ```
> 
> Do you need more logs?

You're manually run the action, right? Please remove `workflow_dispatch` and only trigger it by `create_release`. If you really want to run it manully, you have to set up some more parameters, e.g., where to upload the asset.

**Comment by rsubr** [comment]
> You're manually run the action, right?

You're correct! The release trigger built the binaries and uploaded them successfully. The manual run failed.

It would be great if you could please improve the documentation so it's easy for new users like myself.

Thanks for the great work :-)

**Comment by ioogle** [comment]
> How frequent? Could you please also show me a little more context, i.e., more logs?

Hi youcao, sorry for the late reply, its almost 3/4. The yml file is:

```yaml
name: Release Go Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      GOPRIVATE: github.com/ioogle
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}

      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - name: Build Go Binary (warehouse-api)
        uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/api"
          binary_name: "warehouse-api"
          pre_command: "cd ./warehouse; git config --global url.\"https://ioogle:${{ secrets.ACCESS_TOKEN }}@github.com\".insteadOf \"https://github.com\"; go mod download"
          ldflags: -X "main.appVersion=${{ github.event.release.tag_name }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
          asset_name: warehouse-api-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
```
