### ISSUE TITLE
curl 'https://golang.org/VERSION?m=text' returns <a href="https://go.dev/VERSION?m=text">Moved Permanently</a>

### ISSUE THREAD

**Issue by raykov** [wangyoucao577/go-release-action#66]
Hello, thank you for the cool release action.

I faced this issue when try to use latest version of Golang

```yaml
      - uses: wangyoucao577/go-release-action@v1.21
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.17.3
```

```bash
+ source /setup-go.sh
+++ curl 'https://golang.org/VERSION?m=text'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    64  100    64    0     0    593      0 --:--:-- --:--:-- --:--:--   598
++ GO_LINUX_PACKAGE_URL='https://dl.google.com/go/<a href="https://go.dev/VERSION?m=text">Moved Permanently</a>..linux-amd64.tar.gz'
++ [[ 1.17.3 == \1\.\1\7 ]]
++ [[ 1.17.3 == \1\.\1\6 ]]
++ [[ 1.17.3 == \1\.\1\5 ]]
++ [[ 1.17.3 == \1\.\1\4 ]]
++ [[ 1.17.3 == \1\.\1\3 ]]
++ [[ 1.17.3 == http* ]]
++ wget --progress=dot:mega 'https://dl.google.com/go/<a' 'href="https://go.dev/VERSION?m=text">Moved' 'Permanently</a>..linux-amd64.tar.gz' -O go-linux.tar.gz
--2021-11-22 20:39:47--  https://dl.google.com/go/%3Ca
Resolving dl.google.com (dl.google.com)... 142.250.68.14, 2607:f8b0:4007:80d::200e
Connecting to dl.google.com (dl.google.com)|142.250.68.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-22 20:39:47 ERROR 404: Not Found.

href="https://go.dev/VERSION?m=text">Moved: Scheme missing.
--2021-11-22 20:39:47--  http://permanently%3C/a%3E..linux-amd64.tar.gz
Resolving permanently< (permanently<)... failed: Name or service not known.
wget: unable to resolve host address 'permanently<'
```

---

PR to fix this issue https://github.com/wangyoucao577/go-release-action/pull/67
