### ISSUE TITLE
Go.mod file not found and strange volume mount

### ISSUE THREAD

**Issue by RePrete** [wangyoucao577/go-release-action#69]
I have the following error 
```
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Also I notice a strange volume mounting when starting the action, with a duplicate folder name, the log is 

```
/usr/bin/docker run --name ghcriowangyoucao577goreleaseactionv122_617224 --label 6a6825 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_GOOS -e INPUT_GOARCH -e INPUT_GOVERSION -e INPUT_EXTRA_FILES -e INPUT_BUILD_FLAGS -e INPUT_LDFLAGS -e INPUT_PROJECT_PATH -e INPUT_BINARY_NAME -e INPUT_PRE_COMMAND -e INPUT_BUILD_COMMAND -e INPUT_EXECUTABLE_COMPRESSION -e INPUT_MD5SUM -e INPUT_SHA256SUM -e INPUT_RELEASE_TAG -e INPUT_OVERWRITE -e INPUT_ASSET_NAME -e INPUT_RETRY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/krakend-cached-router/krakend-cached-router":"/github/workspace" ghcr.io/wangyoucao577/go-release-action:v1.22  "***" "linux" "amd64" "https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz" "" "" "." "" "" "go build" "" "LICENSE README.md" "TRUE" "FALSE" "" "FALSE" "" "3"
```

with the interested part 
`-v "/home/runner/work/krakend-cached-router/krakend-cached-router":"/github/workspace"`

My config is:
```
name: Build
on: 
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy artifact
      uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: "https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz"
        extra_files: LICENSE README.md
        build_flags: --buildmode=plugin
```

Other failing tests I did:

- remove `build_flags: --buildmode=plugin`
- project_path: ".."

My source code is inside the [repository ](https://github.com/RePrete/krakend-cached-router)root, what I am doing wrong?
