### ISSUE TITLE
Recommended approach to build module which imports private modules

### ISSUE THREAD

**Issue by maxiride** [wangyoucao577/go-release-action#78]
When using this action to build go modules which imports other private go modules what is the recommended approach to set 
 - GOPRIVATE to explicitly mark an import as private
 - Set git credentials to allow the go get of such private imports?

Usually when building go modules **inside** docker containers I place in the Dockerfile the following commands which pulls the credentials from flags in the docker build command.

```Dockerfile
# git is required to fetch go dependencies
RUN apk add --no-cache ca-certificates git

RUN echo "machine github.com  login $ACCESS_TOKEN_USR password $ACCESS_TOKEN_PWD  machine api.github.com  login $ACCESS_TOKEN_USR password $ACCESS_TOKEN_PWD"  >> /root/.netrc

RUN go env -w GOPRIVATE=github.com/indisrl
```

**Comment by wangyoucao577** [comment]
Both `git` and `ca-certificates` are already available in the docker, see https://github.com/wangyoucao577/go-release-action/blob/master/Dockerfile#L7. Would you please have a try to import the token and set `GOPRIVATE` env by `pre_command`?

**Comment by maxiride** [comment]
I've tried to proceed as suggested with the private module still can't be imported. I recognize there is nothing wrong with the action you made itself but a misconfiguration on my part. I'm circling around with no success if you could please direct me I'd really appreciate that.

Below my workflow configuration and the logs associated to the run.

Run log: https://pastebin.com/sKammSSV
Relevant lines: 404-406

```yml
on: push

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Publish assets
        uses: wangyoucao577/go-release-action@v1.24
        with:
          pre_command: |
            echo "machine github.com login ${{ github.actor }} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
            chmod 600 ~/.netrc
            git config --global --add url."https://github.com/".insteadOf "ssh://git@github.com/"
            git config --global --add url."https://github.com/".insteadOf "git@github.com:"   
            go env -w GOPRIVATE=github.com/indisrl/*
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          goversion: 1.17
          binary_name: test-build
```

**Comment by maxiride** [comment]
TIL that the automatic GITHUB_TOKEN provided in workflows has a limited scope to the repository it is run in.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

>The token's permissions are limited to the repository that contains your workflow. 


I succeeded by:
- generating a new personal access token aka PAT
- adding it to the repository as an action secret
- updating the workflow file to make git use the PAT instead of the GITHUB_TOKEN
- `echo "machine github.com login ${{ github.actor }} password ${{ secrets.PAT}}" > ~/.netrc`

Workflow file:

```yml
on: push

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Publish assets
        uses: wangyoucao577/go-release-action@v1.24
        with:
          pre_command: |
            echo "machine github.com login ${{ github.actor }} password ${{ secrets.PAT  }}" > ~/.netrc
            chmod 600 ~/.netrc
            git config --global --add url."https://github.com/".insteadOf "ssh://git@github.com/"
            git config --global --add url."https://github.com/".insteadOf "git@github.com"   
            go env -w GOPRIVATE=github.com/indisrl/*
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          goversion: 1.17
          binary_name: af-contest
          release_tag: v1.0.0-beta.12
```
