### ISSUE TITLE
How to include multiple binaries in one .zip file ?

### ISSUE THREAD

**Issue by Fadiabb** [wangyoucao577/go-release-action#82]
Hallo, 

We have the following project structure: 
```
├── cmd
│   ├── first
│   │   ├── first.go
│   ├── second
│   │   ├── second.go

```
and want to pack the "first" and "second" binaries in one .zip file.
Calling the action multiple times will generate files  for each binary. 
```yml
on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: ./cmd/first
        binary_name: first
   - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: ./cmd/second
        binary_name: second
```
