### ISSUE TITLE
Change asset_name of only one item in matrix?

### ISSUE THREAD

**Issue by asmaloney** [wangyoucao577/go-release-action#86]
How do I change only "darwin"'s `asset_name`?

My users are not going to understand "darwin", so I wanted to change it to "macos" - something like:

```yaml
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v2
     - uses: wangyoucao577/go-release-action@v1.28
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          if: ${{ matrix.goos }} == 'darwin'
            asset_name: "${BINARY_NAME}-${RELEASE_TAG}-macos-${{ matrix.goarch }}"
```

Obviously this doesn't work since I can't use an `if` there. Is there a clean way to do this?

Thank you!

**Comment by wangyoucao577** [comment]
Yes, you can do this by customize the `asset_name`.         
For example, you can use below steps to set up your `ASSET_NAME` first.      

```
      steps:
      - name: darwin
        if: matrix.goos == 'darwin'
        run: echo "ASSET_NAME=macos" >> $GITHUB_ENV
      - name: not darwin
        if: matrix.goos != 'darwin'
        run: echo "ASSET_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
```    
Then use 
`asset_name:  ${{ env.ASSET_NAME }}`       
in this action.       

The value can be passed via [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) or [envionment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable).           

Please debug it if there's something error, since I didn't tested it out.

**Comment by asmaloney** [comment]
Thank you so much Jay! I'm not very fluent in "GitHub Workflow", but that makes sense 😄 

I'll give it a try on my next release.

**Comment by asmaloney** [comment]
Just to give a complete solution, here's what I did:
```
    steps:
      - name: Get Release Info
        run: |
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "OS_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
      - name: OS darwin
        if: matrix.goos == 'darwin'
        run: echo "OS_NAME=macOS" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          md5sum: false
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: doc examples scripts CHANGELOG.md CITATION.cff CONTRIBUTING.md LICENSE README.md
          asset_name: '${{ env.REPOSITORY_NAME }}-${{ env.RELEASE_TAG }}-${{ env.OS_NAME }}-${{ matrix.goarch }}'
```

If you want to add another example, here's where I use it:

  https://github.com/asmaloney/gactar/blob/main/.github/workflows/release.yaml

Thanks again Jay!
