### ISSUE TITLE
What permissions are required by this action?

### ISSUE THREAD

**Issue by 2color** [wangyoucao577/go-release-action#87]
I tried running this action with the following permissions:

```yaml
    permissions:
      packages: write
```

```yaml
on:
  release:
    types: [created]


jobs:
  releases-matrix:
    permissions:
      packages: write
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.29
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.18
        extra_files: LICENSE.md README.md
```

and it failed. 

```
github-assets-uploader -logtostderr -f auspinner-0.1.0-windows-amd64.zip -mediatype application/zip -repo 2color/auspinner -token *** -tag=0.1.0 -releasename= -retry 3
W0623 08:54:51.996698    3056 main.go:58] Upload asset error, will retry in 3s: Post 
```

What are the [necessary permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for this to run?
