### ISSUE TITLE
Error: Github Assets Uploader - tag or releasename is mandatory but not set

### ISSUE THREAD

**Issue by nea** [wangyoucao577/go-release-action#97]
Ahoy

I try to make three builds: linux, darwin, windows.

Linux works. Darwin and Windows fail with the same message: `tag or releasename is mandatory but not set` 
The command before is `github-assets-uploader -logtostderr -f repo-v0.0.1--.tar.gz -mediatype application/gzip -repo repo/name -token -tag=v0.0.1 -releasename= -retry 3` so a tag is given but still the error.

The workflow is as follows
```
on:
  release:
    types: [ created ]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64

  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: wangyoucao577/go-release-action@v1.32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: darwin

  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: wangyoucao577/go-release-action@v1.32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: windows
```

What am I missing here?

Any help is appreciated.

Thanks
